// Each entry represents one PLU code. Fields:
//   plu       — IFPS-assigned 4-digit code (conventional produce starts with 3 or 4;
//               prefix 9 = organic equivalent, e.g. 94011 for organic banana)
//   name      — common grocery display name
//   variety   — variety or sub-type shown in-game as a hint
//   emoji     — single emoji used as the visual representation
//   image     — Wikimedia Commons photo URL
//   fact      — interesting tidbit revealed after each round
//   quality   — how to distinguish from similar varieties, or quality indicators
//   memoryTip — mnemonic or trick for remembering this PLU

const PRODUCE_DATA = [
  // ===== APPLES =====
  {
    plu: "3507",
    name: "Cosmic Crisp Apple",
    variety: "Crisp, sweet-tart hybrid",
    emoji: "🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Cosmic_Crisp.jpg/960px-Cosmic_Crisp.jpg",
    fact: "Cosmic Crisp was developed at Washington State University over 20 years — a cross between Honeycrisp and Enterprise.",
    quality: "Look for deep red skin with tiny pale lenticels (the 'cosmos' specks that give it the name). Stays crisp for over a year in cold storage. Sweeter than Granny Smith, more acidic than Fuji.",
    memoryTip: "3-5-0-7: 'thirty-five-oh-seven, Cosmic's heaven.'",
  },
  {
    plu: "3616",
    name: "Envy Apple",
    variety: "Sweet, slow-browning",
    emoji: "🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Envy_Apple.jpg",
    fact: "Envy is a New Zealand cross between Royal Gala and Braeburn, prized for resisting browning when sliced.",
    quality: "Bright red with golden flecks. Very firm, sweet, and floral — minimal tartness. Great for snacking and salads because cut slices stay white for hours.",
    memoryTip: "3-6-1-6: '36-16, Envy is keen.'",
  },
  {
    plu: "4131",
    name: "Fuji Apple",
    variety: "Sweet & crisp",
    emoji: "🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Apfel-Fuji.jpg/960px-Apfel-Fuji.jpg",
    fact: "Fujis were developed in Japan in the 1930s as a cross between Red Delicious and Ralls Janet.",
    quality: "vs Gala (4135): Fuji is larger, denser, and much crunchier with a honey-sweet flavour. Gala is softer, smaller, and milder. Choose firm Fujis with no soft spots.",
    memoryTip: "4-1-3-1: Fuji comes just after 4130 (Pink Lady) — one step up.",
  },
  {
    plu: "4135",
    name: "Gala Apple",
    variety: "Mildly sweet",
    emoji: "🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Gala_apples_on_cloth.jpg/960px-Gala_apples_on_cloth.jpg",
    fact: "Gala apples originated in New Zealand and are now the top-selling apple variety in the US.",
    quality: "vs Fuji (4131): Gala is softer, smaller, and milder — better for kids. vs Honeycrisp (3283): Gala is less expensive and less tart. Choose firm ones with bright red-orange stripes.",
    memoryTip: "4-1-3-5: Fuji is 4131, Gala is four higher — 4135.",
  },
  {
    plu: "4017",
    name: "Granny Smith Apple",
    variety: "Tart green apple",
    emoji: "🍏",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Granny_smith_and_cross_section.jpg/960px-Granny_smith_and_cross_section.jpg",
    fact: "Named after Maria Ann 'Granny' Smith of Australia, who discovered the cultivar around 1868.",
    quality: "Unmistakably bright green and tart — no real lookalike in stores. Avoid apples with any yellow tinge (less tart, past peak). Great for baking because they hold shape.",
    memoryTip: "4-0-1-7: 'forty-oh-seventeen, Granny's lean and green.'",
  },
  {
    plu: "3283",
    name: "Honeycrisp Apple",
    variety: "Crunchy & juicy",
    emoji: "🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Honeycrisp-Apple.jpg/960px-Honeycrisp-Apple.jpg",
    fact: "Honeycrisp's signature 'explosive' crunch comes from unusually large cells that burst when bitten.",
    quality: "Mottled red over yellow background. Always feel for firmness — Honeycrisp loses its crunch fast if stored warm. vs Cosmic Crisp (3507): Honeycrisp is sweeter and less acidic but doesn't keep as long.",
    memoryTip: "3-2-8-3: '32-83, honey-crisp tree.'",
  },
  {
    plu: "4130",
    name: "Pink Lady Apple",
    variety: "Tart-sweet, late season",
    emoji: "🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/960px-Pink_lady_and_cross_section.jpg",
    fact: "Pink Lady is a brand name for the Cripps Pink cultivar — only fruit meeting strict colour and sugar standards earns the name.",
    quality: "Distinctive pink-red blush over yellow. Very firm with a champagne-like tart-sweet bite. One of the latest apples to harvest, so quality stays high through winter.",
    memoryTip: "4-1-3-0: Pink Lady is 4130 — Fuji (4131) is one higher.",
  },
  {
    plu: "3486",
    name: "SugarBee Apple",
    variety: "Honeycrisp descendant",
    emoji: "🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Honeycrisp-Apple.jpg/960px-Honeycrisp-Apple.jpg",
    fact: "SugarBee was discovered as a chance seedling in a Minnesota field — likely pollinated by bees from a Honeycrisp orchard.",
    quality: "Pink-red skin with creamy yellow undertones. Sweeter than its Honeycrisp parent with a sturdier crunch. Look for a sticker — it's a managed variety with limited supply.",
    memoryTip: "3-4-8-6: '34-86, SugarBee's a treat.'",
  },

  // ===== AVOCADOS =====
  {
    plu: "4225",
    name: "Hass Avocado",
    variety: "Small-medium",
    emoji: "🥑",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Avocado_Hass_-_single_and_halved.jpg/960px-Avocado_Hass_-_single_and_halved.jpg",
    fact: "Named after Rudolph Hass, a California mail carrier who patented the tree in 1935.",
    quality: "vs Florida avocado (4249): Hass is smaller, turns dark and pebbly when ripe, richer and creamier. Florida avocado is larger, stays green, and has lower fat. Ripe Hass yields to gentle pressure near the stem.",
    memoryTip: "4-2-2-5: 'forty-two twenty-five, the avocado's alive.'",
  },
  {
    plu: "94046",
    name: "Organic Hass Avocado",
    variety: "Organic",
    emoji: "🥑",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Avocado_Hass_-_single_and_halved.jpg/960px-Avocado_Hass_-_single_and_halved.jpg",
    fact: "The leading 9 marks organic; the underlying 4046 is the legacy small-Hass code (now usually merged with 4225 for conventional).",
    quality: "Same look-and-feel test as conventional Hass: dark, pebbly skin and gentle give near the stem. Organic skins are sometimes thinner — handle gently.",
    memoryTip: "9-4-0-4-6: a 9 in front always means organic; remember 4046 = the avocado's organic alter ego.",
  },

  // ===== BANANA =====
  {
    plu: "4011",
    name: "Banana",
    variety: "Yellow, conventional",
    emoji: "🍌",
    image: "https://upload.wikimedia.org/wikipedia/commons/d/de/Bananavarieties.jpg",
    fact: "The most scanned PLU in US grocery history.",
    quality: "Slightly green = ripens at home; bright yellow = ready now; brown-flecked = sweetest for baking. Avoid mushy, blackened stems.",
    memoryTip: "4-0-1-1: the easiest PLU to remember — just think 'the OG banana'.",
  },

  // ===== BERRIES =====
  {
    plu: "3329",
    name: "Blueberries",
    variety: "Fresh pint",
    emoji: "🫐",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Blueberries.jpg",
    fact: "Blueberries are one of the few fruits native to North America and were a staple food for Indigenous peoples.",
    quality: "Choose plump, firm, deep blue-purple berries with a silvery bloom (natural wax coating). Avoid red or green ones (underripe) and shrivelled or mushy ones. Shake the container — berries should move freely, not clump.",
    memoryTip: "3-3-2-9: '33-29, blueberries shine.'",
  },
  {
    plu: "4275",
    name: "Strawberry",
    variety: "Fresh pint",
    emoji: "🍓",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/960px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg",
    fact: "Strawberries are the only fruit with seeds on the outside — around 200 per berry.",
    quality: "Choose fully red berries — white or green tips mean they were picked underripe and will never sweeten. Smell them at the store; ripe strawberries have a strong, sweet fragrance.",
    memoryTip: "4-2-7-5: '42-75, strawberries thrive.'",
  },

  // ===== CITRUS =====
  {
    plu: "4289",
    name: "Grapefruit",
    variety: "Conventional",
    emoji: "🍊",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Grapefruits_-_whole-halved-segments.jpg/960px-Grapefruits_-_whole-halved-segments.jpg",
    fact: "Grapefruit is a natural cross between sweet orange and pomelo, first documented in Barbados in the 1700s.",
    quality: "Choose grapefruits that feel heavy for their size (juicier) with smooth, thin skin. Pink/red varieties are sweeter than white. Skin colour doesn't always indicate ripeness — go by weight.",
    memoryTip: "4-2-8-9: '42-89, grapefruit divine.'",
  },
  {
    plu: "4053",
    name: "Lemon",
    variety: "Conventional",
    emoji: "🍋",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/P1030323.JPG/960px-P1030323.JPG",
    fact: "Lemons are a hybrid of bitter orange and citron, and do not exist as a wild species.",
    quality: "Eureka and Lisbon lemons look nearly identical in stores. Choose firm, heavy lemons with smooth, thin skin — the heavier they are, the juicier. Thick-skinned or light lemons yield less juice.",
    memoryTip: "4-0-5-3: 'four-oh-five-three, squeeze a lemon for me.'",
  },
  {
    plu: "4048",
    name: "Lime",
    variety: "Persian lime",
    emoji: "🍋",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Starr-140117-3997-Citrus_latifolia-Tahitian_fruit_and_leaves-Hawea_Pl_Olinda-Maui_%2824612312943%29.jpg/960px-Starr-140117-3997-Citrus_latifolia-Tahitian_fruit_and_leaves-Hawea_Pl_Olinda-Maui_%2824612312943%29.jpg",
    fact: "Persian limes — the standard grocery lime — are seedless because they are triploid hybrids.",
    quality: "Choose heavy limes with glossy, deep green skin — yellowing means overripe. Small Key limes (rare in chain stores) are rounder, more aromatic, and seedier.",
    memoryTip: "4-0-4-8: lemon is 4053, lime sits just below — 4048.",
  },
  {
    plu: "3632",
    name: "Sumo Mandarin",
    variety: "Easy-peel hybrid",
    emoji: "🍊",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Dekopon_-_Tokyo_area_-_April_16_2019.jpeg/960px-Dekopon_-_Tokyo_area_-_April_16_2019.jpeg",
    fact: "Sumo Citrus is a Japanese cross of mandarin and orange — its distinctive top-knot bump is a varietal trademark.",
    quality: "Identifiable by the bumpy 'top-knot' at the stem end and loose, bumpy skin. Very sweet, low acid, easy to peel. In season January through April; quite expensive.",
    memoryTip: "3-6-3-2: '36-32, Sumo for you.'",
  },
  {
    plu: "4012",
    name: "Orange",
    variety: "Conventional",
    emoji: "🍊",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/960px-Oranges_-_whole-halved-segment.jpg",
    fact: "Oranges are the world's most cultivated tree fruit — over 70 million tonnes are grown annually.",
    quality: "Navel oranges have a belly-button end, are seedless, and are best for eating fresh. Valencias have seeds and are juicier — better for juicing. Choose oranges that feel heavy for their size; weight equals juice.",
    memoryTip: "4-0-1-2: '40-12, oranges shelve.'",
  },
  {
    plu: "3129",
    name: "Pummelo",
    variety: "Asian citrus giant",
    emoji: "🍊",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Pomelo_fruit.jpg/960px-Pomelo_fruit.jpg",
    fact: "Pummelo (or pomelo) is the largest citrus fruit and the ancestor of grapefruit — it can weigh up to 4 kg.",
    quality: "Thick, spongy rind hides surprisingly little juice — most weight is pith. Flesh is sweeter and less bitter than grapefruit, with firm, dry segments that pull apart cleanly.",
    memoryTip: "3-1-2-9: '31-29, pummelo time.'",
  },

  // ===== DRAGON FRUIT =====
  {
    plu: "3319",
    name: "Yellow Dragon Fruit",
    variety: "Selenicereus megalanthus",
    emoji: "🐉",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Hylocereus_megalanthus1EDWARD.jpg/960px-Hylocereus_megalanthus1EDWARD.jpg",
    fact: "Yellow dragon fruit is much sweeter than the pink-skinned varieties — sometimes called Ecuador's golden pitaya.",
    quality: "Yellow knobby skin with white interior flesh and tiny black seeds. Sweeter and more aromatic than the pink-skinned types. Ripe when it gives slightly to pressure.",
    memoryTip: "3-3-1-9: '33-19, yellow dragon's fine.'",
  },
  {
    plu: "3040",
    name: "Snow Dragon Fruit",
    variety: "White-fleshed pitaya",
    emoji: "🐉",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Pitaya_cross_section_ed2.jpg/960px-Pitaya_cross_section_ed2.jpg",
    fact: "Dragon fruit is a cactus fruit — pollinated at night by bats and moths, hence the bright skin to attract them.",
    quality: "Bright pink-red skin with white flesh and tiny black seeds. Mildly sweet, kiwi-like flavour. Press gently — ripe fruit yields like a ripe avocado. Avoid dry, brown 'leaves' on the outside.",
    memoryTip: "3-0-4-0: '30-40, snow dragon's plenty.'",
  },

  // ===== GRAPES =====
  {
    plu: "4022",
    name: "Green Grapes",
    variety: "Thompson seedless",
    emoji: "🍇",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Table_grapes_on_white.jpg/960px-Table_grapes_on_white.jpg",
    fact: "Thompson seedless grapes are also the primary grape used to make raisins.",
    quality: "vs red grapes (4498): green are crunchier and more tart, red are sweeter. Choose firm grapes still attached to stems. A faint white bloom (dusty coating) is natural and a sign of freshness.",
    memoryTip: "4-0-2-2: 'four-oh-two-two, green grapes for you.'",
  },

  // ===== KIWI =====
  {
    plu: "3279",
    name: "Kiwi",
    variety: "Green, conventional",
    emoji: "🥝",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Actinidia_fruits.jpg/960px-Actinidia_fruits.jpg",
    fact: "Kiwis were originally called 'Chinese gooseberries' until New Zealand exporters rebranded them in the 1950s.",
    quality: "Green kiwi (3279) is tart and tangy with fuzzy brown skin. vs golden kiwi: smoother skin, sweeter, less acidic. Choose kiwis that yield slightly to pressure — rock-hard ones need several days on the counter to ripen.",
    memoryTip: "3-2-7-9: '32-79, kiwi's fine.'",
  },

  // ===== MANGOES =====
  {
    plu: "4959",
    name: "Mango",
    variety: "Tommy Atkins / conventional",
    emoji: "🥭",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mangos_-_single_and_halved.jpg/960px-Mangos_-_single_and_halved.jpg",
    fact: "Mangoes are the most consumed fruit in the world by weight.",
    quality: "Don't judge by skin colour — judge by feel. A ripe mango yields slightly to pressure near the stem and smells sweet and floral. Tommy Atkins (red/green skin) is the most common in US stores.",
    memoryTip: "4-9-5-9: '49-59, mango on the vine.'",
  },
  {
    plu: "4312",
    name: "Ataulfo Mango",
    variety: "Yellow, kidney-shaped",
    emoji: "🥭",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Yay%2C_the_Ataulfos_Have_Arrived.jpg/960px-Yay%2C_the_Ataulfos_Have_Arrived.jpg",
    fact: "Ataulfo mangoes (also called Honey or Champagne) are nearly fibreless and have a small, flat pit — the highest flesh-to-seed ratio of any common mango.",
    quality: "vs Tommy Atkins (4959): Ataulfo is smaller, golden-yellow, kidney-shaped, far creamier and less stringy. Ripe when the skin is wrinkled and soft like a ripe avocado — green ones are not ready.",
    memoryTip: "4-3-1-2: '43-12, Ataulfo elf.'",
  },

  // ===== MELONS =====
  {
    plu: "4050",
    name: "Cantaloupe",
    variety: "Whole conventional",
    emoji: "🍈",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Meloen_vrucht_met_bloem.jpg",
    fact: "Cantaloupes are named after Cantalupo, a papal estate near Rome where they were first cultivated in Europe.",
    quality: "vs honeydew (4329): cantaloupe has rough tan netting and orange flesh; honeydew has smooth pale skin and green flesh. Ripe cantaloupe smells sweet at the stem end and yields slightly. The stem end should have a smooth indent, not a stub.",
    memoryTip: "4-0-5-0: '40-50, cantaloupe nifty.'",
  },
  {
    plu: "4326",
    name: "Galia Melon",
    variety: "Israeli hybrid",
    emoji: "🍈",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Lebensmittel-Galiamelone1-Asio.JPG/960px-Lebensmittel-Galiamelone1-Asio.JPG",
    fact: "Galia is a 1970s Israeli cross of cantaloupe and honeydew — netted skin like a cantaloupe but pale green flesh.",
    quality: "Tan-yellow netted rind with light green flesh. Sweet, floral, and aromatic when ripe. Ripeness signal: the rind turns from green to gold, and the blossom end gives slightly.",
    memoryTip: "4-3-2-6: '43-26, Galia in the mix.'",
  },
  {
    plu: "4329",
    name: "Honeydew Melon",
    variety: "Whole conventional",
    emoji: "🍈",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Honeydew.jpg/960px-Honeydew.jpg",
    fact: "Unlike cantaloupes, honeydew melons do not slip from the vine when ripe — they must be cut.",
    quality: "vs cantaloupe (4050): honeydew has smooth, pale cream-green skin and green flesh; cantaloupe has rough tan netting and orange flesh. A ripe honeydew feels heavy, has a slightly waxy skin, and smells faintly sweet at the blossom end.",
    memoryTip: "4-3-2-9: cantaloupe 4050, honeydew is higher — 4329.",
  },
  {
    plu: "95369",
    name: "Organic Sugar Kiss Melon",
    variety: "Premium netted melon",
    emoji: "🍈",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Meloen_vrucht_met_bloem.jpg",
    fact: "Sugar Kiss is a branded melon variety bred for unusually high sugar content — often 14–16 brix, sweeter than typical cantaloupe.",
    quality: "Heavy, golden-tan rind with deep netting. Aroma at stem end is strong and sweet. Sold organic-only under the Sugar Kiss label.",
    memoryTip: "9-5-3-6-9: prefix 9 = organic; '53-69, Sugar Kiss is fine.'",
  },
  {
    plu: "4332",
    name: "Tuscan Cantaloupe",
    variety: "Italian-style melon",
    emoji: "🍈",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Meloen_vrucht_met_bloem.jpg",
    fact: "Tuscan cantaloupes are derived from Italian Mediterranean melons, with deep green sutures dividing the rind into ribbed segments.",
    quality: "Distinctive deep green ribbed sutures over a tan rind. Flesh is denser and more aromatic than standard cantaloupe. Ripe when sutures yellow slightly and stem end smells fragrant.",
    memoryTip: "4-3-3-2: '43-32, Tuscan true.'",
  },
  {
    plu: "4032",
    name: "Watermelon (Large)",
    variety: "Seedless whole",
    emoji: "🍉",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg/960px-Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg",
    fact: "Watermelons are 92% water — hence the name.",
    quality: "Look for a creamy yellow field spot (where it sat on the ground) — white or absent means it was picked too early. Should feel heavy for its size and sound hollow when thumped.",
    memoryTip: "4-0-3-2: large watermelon is 4032 — mini is 3421.",
  },
  {
    plu: "3421",
    name: "Mini Watermelon",
    variety: "Personal seedless",
    emoji: "🍉",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg/960px-Taiwan_2009_Tainan_City_Organic_Farm_Watermelon_FRD_7962.jpg",
    fact: "Mini ('personal') watermelons were developed in the 2000s for single-serving households and small fridges.",
    quality: "Same field-spot rule as full-size watermelon: creamy yellow good, white bad. About the size of a cantaloupe. Heavier feel = juicier flesh.",
    memoryTip: "3-4-2-1: mini watermelon 3421 — large is 4032.",
  },

  // ===== STONE FRUIT =====
  {
    plu: "4378",
    name: "Yellow Nectarine",
    variety: "Conventional",
    emoji: "🍑",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Nectarine_on_white.jpg/960px-Nectarine_on_white.jpg",
    fact: "Nectarines are not a hybrid — they're peaches with a recessive gene that produces smooth skin instead of fuzz.",
    quality: "vs peach (4044): nectarines have smooth skin, peaches are fuzzy — flavour is nearly identical. Choose nectarines that smell fragrant and yield slightly when pressed gently near the stem.",
    memoryTip: "4-3-7-8: '43-78, nectarine date.'",
  },
  {
    plu: "4044",
    name: "Yellow Peach",
    variety: "Conventional",
    emoji: "🍑",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/960px-Illustration_Prunus_persica_clean_no_descr.jpg",
    fact: "Peaches belong to the rose family, along with apples, pears, cherries, and almonds.",
    quality: "vs nectarine (4378): peaches are fuzzy, nectarines smooth — flavour is nearly identical. Freestone pits separate easily (better for eating fresh); clingstone pits cling to the flesh. Choose peaches that smell fragrant and yield gently near the stem.",
    memoryTip: "4-0-4-4: '40-44, peach galore.'",
  },

  // ===== PEARS =====
  {
    plu: "4408",
    name: "Asian Pear",
    variety: "Apple-shaped, crisp",
    emoji: "🍐",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Nashi_pear.jpg/960px-Nashi_pear.jpg",
    fact: "Asian pears are sometimes called 'apple pears' for their round shape and crunchy texture — they ripen on the tree, not after picking.",
    quality: "Round like an apple, crisp like an apple, but with pear flavour and grainy flesh. Skin ranges from pale yellow to russet brown. Ripe when fragrant — they don't soften like Bartletts.",
    memoryTip: "4-4-0-8: '44-08, Asian pear's great.'",
  },
  {
    plu: "4409",
    name: "Bartlett Pear",
    variety: "Yellow, conventional",
    emoji: "🍐",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Bartlett_pear.jpg/960px-Bartlett_pear.jpg",
    fact: "Bartlett pears are known as Williams pears in most of the world outside North America.",
    quality: "vs Bosc (4413): Bartlett is softer, juicier, and bell-shaped, turning yellow when ripe; Bosc is firmer, brown-skinned, and holds shape when cooked. vs D'Anjou (4416): D'Anjou stays green even when ripe. Check near the neck — ripe Bartlett yields gently there.",
    memoryTip: "4-4-0-9: '44-09, Bartlett's divine.'",
  },
  {
    plu: "4413",
    name: "Bosc Pear",
    variety: "Russeted brown",
    emoji: "🍐",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/BoscPears.jpg/960px-BoscPears.jpg",
    fact: "Bosc pears retain their shape when cooked, making them the preferred pear for poaching and baking.",
    quality: "Russeted bronze-brown skin and a long tapered neck. Firmer than Bartlett even when ripe — a slight give at the neck means ready to eat. Sweet, spicy flavour.",
    memoryTip: "4-4-1-3: '44-13, Bosc is bronze.'",
  },
  {
    plu: "4416",
    name: "D'Anjou Pear",
    variety: "Green, all-purpose",
    emoji: "🍐",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/D%27anjou_pear.jpg/960px-D%27anjou_pear.jpg",
    fact: "D'Anjou pears stay green even when fully ripe — colour change is not a ripeness indicator.",
    quality: "Egg-shaped with smooth green skin that doesn't change colour as it ripens. Press gently at the neck — slight give means ready. Mild, sweet flavour; good for both eating and cooking.",
    memoryTip: "4-4-1-6: '44-16, D'Anjou green.'",
  },
  {
    plu: "4417",
    name: "Red D'Anjou Pear",
    variety: "Burgundy-skinned",
    emoji: "🍐",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/D%27anjou_pear.jpg/960px-D%27anjou_pear.jpg",
    fact: "Red D'Anjou is a natural mutation of the green D'Anjou, discovered in a Washington orchard in the 1950s.",
    quality: "Same shape and texture as green D'Anjou but with maroon-red skin. Same ripeness test — press at the neck for slight give. Skin colour does not change with ripeness.",
    memoryTip: "4-4-1-7: green D'Anjou 4416, red is one higher — 4417.",
  },
  {
    plu: "4425",
    name: "Korean Shingo Pear",
    variety: "Large Asian pear",
    emoji: "🍐",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Shinko_Yali_and_Whangkeum.JPG/960px-Shinko_Yali_and_Whangkeum.JPG",
    fact: "Shingo pears can grow to nearly 1 kg each — among the largest pears commercially sold.",
    quality: "Large round Asian pear with golden-tan skin and exceptionally crisp, juicy flesh. Often individually wrapped to prevent bruising. Eat soon after the skin softens slightly.",
    memoryTip: "4-4-2-5: '44-25, Shingo's alive.'",
  },

  // ===== PINEAPPLE =====
  {
    plu: "4430",
    name: "Pineapple",
    variety: "Whole conventional",
    emoji: "🍍",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg/960px-%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg",
    fact: "It takes about 18 months to grow a single pineapple plant to harvest.",
    quality: "Ignore colour — a green pineapple can be fully ripe. Judge by smell (sweet at the base) and firmness (slight give, not mushy). Gold pineapples (Del Monte Extra Sweet) are sweeter and more golden than standard.",
    memoryTip: "4-4-3-0: '44-30, pineapple gold.'",
  },

  // ===== POMEGRANATE / PERSIMMON / PAPAYA =====
  {
    plu: "3127",
    name: "Pomegranate",
    variety: "Whole conventional",
    emoji: "🍎",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Pomegranate_fruit_-_whole_and_piece_with_arils.jpg/960px-Pomegranate_fruit_-_whole_and_piece_with_arils.jpg",
    fact: "A single pomegranate can hold over 600 arils (juice-filled seed sacs).",
    quality: "Choose pomegranates that feel heavy for their size with deep red, slightly leathery skin. A few brown spots are fine; soft spots are not. Heavier = juicier arils.",
    memoryTip: "3-1-2-7: '31-27, pomegranate seven.'",
  },
  {
    plu: "4428",
    name: "Persimmon",
    variety: "Fuyu / Hachiya",
    emoji: "🍅",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Fuyu_persimmon_fruits%2C_one_cut_open.jpg/960px-Fuyu_persimmon_fruits%2C_one_cut_open.jpg",
    fact: "Fuyu persimmons can be eaten firm like an apple, but Hachiya must be jelly-soft or they'll be mouth-puckeringly astringent.",
    quality: "Fuyu = squat, tomato-shaped, eat firm. Hachiya = acorn-shaped, must be very soft and jelly-like before eating. Both are bright orange. Don't confuse the two — biting an unripe Hachiya is unforgettable.",
    memoryTip: "4-4-2-8: '44-28, persimmon date.'",
  },
  {
    plu: "3112",
    name: "Papaya",
    variety: "Whole conventional",
    emoji: "🥭",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg/960px-Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg",
    fact: "Papayas contain papain, an enzyme used commercially as a meat tenderizer.",
    quality: "Ripe papaya is mostly yellow-orange skin with slight give. Green papayas are unripe and used in Southeast Asian salads. Avoid wrinkled or fermented-smelling fruit.",
    memoryTip: "3-1-1-2: '31-12, papaya delivers.'",
  },

  // ===== TOMATOES =====
  {
    plu: "4087",
    name: "Roma Tomato",
    variety: "Conventional",
    emoji: "🍅",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/TomateTrossRomanaTyp.jpg/960px-TomateTrossRomanaTyp.jpg",
    fact: "Tomatoes are botanically a fruit but were legally declared a vegetable by the US Supreme Court in 1893.",
    quality: "vs beefsteak (4799): Roma is firmer, meatier, and less watery — ideal for sauces and cooking. Beefsteak is larger, juicier, and better for slicing fresh. Choose Romas with deep red, unblemished skin.",
    memoryTip: "4-0-8-7: 'four-oh-eight-seven, Roma's heaven.'",
  },
  {
    plu: "4799",
    name: "Beefsteak Tomato",
    variety: "Large slicing tomato",
    emoji: "🍅",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Diversit%C3%A9_taille_tomates.jpg/960px-Diversit%C3%A9_taille_tomates.jpg",
    fact: "Beefsteak tomatoes can weigh over a pound each — among the largest cultivated tomato varieties.",
    quality: "vs Roma (4087): beefsteak is larger, juicier, and better for slicing fresh; Roma is firmer and better for sauces. Choose tomatoes that smell faintly sweet at the stem and feel heavy.",
    memoryTip: "4-7-9-9: '47-99, beefsteak fine.'",
  },

  // ===== CRUCIFEROUS / GREENS =====
  {
    plu: "3082",
    name: "Broccoli",
    variety: "Fresh crown",
    emoji: "🥦",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Broccoli_and_cross_section_edit.jpg/960px-Broccoli_and_cross_section_edit.jpg",
    fact: "Broccoli is 90% water and one of the most nutrient-dense vegetables by weight.",
    quality: "Choose dark green, tightly packed florets with no yellowing. Stems should snap crisply, not bend. Yellow florets mean it's past its peak.",
    memoryTip: "3-0-8-2: 'three-oh-eight-two, broccoli's true.'",
  },
  {
    plu: "3083",
    name: "Brussels Sprout Stalks",
    variety: "Whole stalks",
    emoji: "🥦",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Brussels_sprout_closeup.jpg/960px-Brussels_sprout_closeup.jpg",
    fact: "Brussels sprouts grow on a thick stalk, with up to 40 sprouts per plant — the stalk version is the freshest you can buy.",
    quality: "Sprouts should be tight, bright green, and uniform in size. Yellow leaves or strong cabbage smell mean it's past its peak. Whole stalks keep longer than loose sprouts.",
    memoryTip: "3-0-8-3: broccoli 3082, brussels stalk one higher — 3083.",
  },
  {
    plu: "4070",
    name: "Celery",
    variety: "Conventional stalk",
    emoji: "🥬",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Celery_1.jpg/960px-Celery_1.jpg",
    fact: "Celery was used as a medicinal plant in ancient Rome and Greece long before it became a food crop.",
    quality: "Choose firm, tightly packed stalks with fresh, green leaves — wilted leaves or hollow stalks mean it's old. Stalks should snap crisply, not bend. Lighter green stalks are more tender; darker outer stalks are more flavourful.",
    memoryTip: "4-0-7-0: '40-70, celery to go.'",
  },

  // ===== ROOTS / BULBS =====
  {
    plu: "4562",
    name: "Carrot",
    variety: "Loose, conventional",
    emoji: "🥕",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/960px-Vegetable-Carrot-Bundle-wStalks.jpg",
    fact: "Carrots were originally purple and white — the orange variety was cultivated in the Netherlands in the 17th century.",
    quality: "Loose carrots vs bagged baby carrots: loose are often fresher and more flavourful. Choose firm, smooth, bright orange carrots. Smaller diameter = more tender and sweet. Avoid limp or cracked ones.",
    memoryTip: "4-5-6-2: '45-62, carrots on cue.'",
  },
  {
    plu: "4608",
    name: "Garlic",
    variety: "Conventional bulb",
    emoji: "🧄",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Garlic_bulb.jpg/960px-Garlic_bulb.jpg",
    fact: "Garlic has been used medicinally for over 5,000 years, including by Egyptian pyramid workers.",
    quality: "Choose firm, tight bulbs with dry papery skin. Avoid any soft spots or green sprouts — sprouted cloves taste bitter. Hardneck varieties have more complex flavour than softneck; softneck lasts longer.",
    memoryTip: "4-6-0-8: '46-08, garlic at the gate.'",
  },
  {
    plu: "4662",
    name: "Shallot",
    variety: "Loose bulbs",
    emoji: "🧅",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/22/Shallots_-_sliced_and_whole.jpg",
    fact: "Shallots are a distinct species from onions — milder, sweeter, and lower in tear-inducing sulfur compounds.",
    quality: "Choose firm bulbs with dry, coppery skin and no soft spots or sprouts. Smaller shallots are usually sweeter. The papery skin should rustle when squeezed.",
    memoryTip: "4-6-6-2: '46-62, shallot for you.'",
  },

  // ===== ONIONS =====
  {
    plu: "4082",
    name: "Red Onion",
    variety: "Conventional",
    emoji: "🧅",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Red_Onion_on_White.JPG/960px-Red_Onion_on_White.JPG",
    fact: "Red onions get their colour from anthocyanins — the same antioxidants that colour blueberries and red cabbage.",
    quality: "Milder and sweeter than yellow onion, ideal raw on salads and sandwiches. Choose firm bulbs with crisp papery skin and no green sprouts. Cut surface should be deep purple-red throughout.",
    memoryTip: "4-0-8-2: red 4082, yellow 4093, white 4663, sweet 4166.",
  },
  {
    plu: "4166",
    name: "Sweet Onion",
    variety: "Vidalia / Walla Walla",
    emoji: "🧅",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Hillview_Farms_Vidalia_onions.jpg/960px-Hillview_Farms_Vidalia_onions.jpg",
    fact: "Sweet onions like Vidalia are sweet because they grow in low-sulfur soil, not because they have more sugar.",
    quality: "Larger, flatter, and milder than yellow onions. Skin is light golden and looser. Best raw or quickly cooked — too watery for long caramelizing. Choose firm onions with dry, intact skin.",
    memoryTip: "4-1-6-6: '41-66, sweet onion mix.'",
  },
  {
    plu: "4663",
    name: "White Onion",
    variety: "Conventional",
    emoji: "🧅",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Starr_070730-7815_Allium_cepa.jpg/960px-Starr_070730-7815_Allium_cepa.jpg",
    fact: "White onions are the standard for Mexican cuisine — sharper raw and crisper than yellow onions.",
    quality: "Sharper and more pungent raw than yellow or red. Pure white skin and flesh. Choose firm, dry bulbs with no soft spots or green sprouts.",
    memoryTip: "4-6-6-3: white 4663 — sits right next to shallot 4662.",
  },
  {
    plu: "4093",
    name: "Yellow Onion",
    variety: "Conventional",
    emoji: "🧅",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Onion_white_background.jpg/960px-Onion_white_background.jpg",
    fact: "Yellow onions become sweet and caramelized when cooked because their sulfur compounds convert to sugars.",
    quality: "vs white onion (4663): yellow is more complex and sweeter when cooked; white is sharper raw. vs red onion (4082): red is milder raw and used in salads. Choose firm, dry onions — avoid any with soft spots or green sprouts.",
    memoryTip: "4-0-9-3: 'four-oh-nine-three, yellow onion's free.'",
  },

  // ===== PEPPERS =====
  {
    plu: "4065",
    name: "Green Bell Pepper",
    variety: "Conventional",
    emoji: "🫑",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Green-Bell-Pepper.jpg/960px-Green-Bell-Pepper.jpg",
    fact: "Green bell peppers are simply unripe red, yellow, or orange peppers — picked early before they sweeten.",
    quality: "More bitter and less sweet than red (4688) or yellow (4689) bells because they haven't developed sugars yet. Choose firm, glossy, unwrinkled peppers. Wrinkling means moisture loss and age.",
    memoryTip: "4-0-6-5: green is 4065, red is 4688 — green is lower because it's less ripe.",
  },
  {
    plu: "3121",
    name: "Orange Bell Pepper",
    variety: "Conventional",
    emoji: "🫑",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Orange_pepper.jpg/960px-Orange_pepper.jpg",
    fact: "Orange bell peppers are a distinct cultivar — they ripen orange instead of progressing from green to red.",
    quality: "Sweetness sits between yellow (4689) and red (4688). Choose firm, glossy peppers with no soft spots. Heavy weight for size means thick walls.",
    memoryTip: "3-1-2-1: '31-21, orange pepper's fun.'",
  },
  {
    plu: "4688",
    name: "Red Bell Pepper",
    variety: "Conventional",
    emoji: "🫑",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Red_bell_pepper.jpg/960px-Red_bell_pepper.jpg",
    fact: "Red bell peppers have 11 times more beta-carotene and 3 times more vitamin C than green bell peppers.",
    quality: "Red, yellow, and orange bells are fully ripened — sweeter and less bitter than green (4065), which is unripe. Red has an earthy sweetness; yellow is milder; orange is in between. Choose firm peppers that feel heavy with glossy skin.",
    memoryTip: "4-6-8-8: '46-88, red bell's great.'",
  },
  {
    plu: "4689",
    name: "Yellow Bell Pepper",
    variety: "Conventional",
    emoji: "🫑",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Yellow_bell_pepper.jpg/960px-Yellow_bell_pepper.jpg",
    fact: "Yellow bells fall between green (unripe) and red (fully ripe) on the ripeness spectrum, with mild fruity sweetness.",
    quality: "Milder and slightly tangier than red (4688) or orange (3121). Choose firm, glossy peppers with no wrinkling. Red 4688, yellow is right next door — 4689.",
    memoryTip: "4-6-8-9: red 4688, yellow 4689 — yellow is one higher.",
  },
  {
    plu: "4693",
    name: "Jalapeño",
    variety: "Singles, conventional",
    emoji: "🌶️",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Immature_jalapeno_capsicum_annuum_var_annuum.jpeg/960px-Immature_jalapeno_capsicum_annuum_var_annuum.jpeg",
    fact: "Jalapeños left to ripen and dry become chipotles — the same pepper, smoked instead of fresh.",
    quality: "Choose firm, glossy peppers — wrinkles or 'corking' (white striations) on the skin indicate older, hotter peppers. Larger, smoother jalapeños tend to be milder.",
    memoryTip: "4-6-9-3: '46-93, jalapeño heat.'",
  },

  // ===== POTATOES =====
  {
    plu: "4727",
    name: "Gold Potato",
    variety: "Yukon Gold",
    emoji: "🥔",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Yukon-gold-potatoes.jpg",
    fact: "Yukon Gold was developed at the University of Guelph in Ontario and released in 1980.",
    quality: "Buttery yellow flesh, thin gold skin. Holds shape better than russet (4072), starchier than red (4073) — true all-purpose potato. Choose firm tubers; avoid green-tinged or sprouted ones.",
    memoryTip: "4-7-2-7: '47-27, gold potato's seven.'",
  },
  {
    plu: "4073",
    name: "Red Potato",
    variety: "Waxy, all-purpose",
    emoji: "🥔",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Patates.jpg/960px-Patates.jpg",
    fact: "Red potatoes hold their shape after cooking better than starchy varieties — ideal for potato salad and stews.",
    quality: "Thin red skin, white waxy flesh. vs russet (4072): reds are waxier, hold shape; russets are starchy, fluffy. Choose smooth, firm potatoes — wrinkled or sprouted means old.",
    memoryTip: "4-0-7-3: russet 4072, red is one higher — 4073.",
  },
  {
    plu: "4072",
    name: "Russet Potato",
    variety: "Conventional",
    emoji: "🥔",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Russet_potato_cultivar_with_sprouts.jpg/960px-Russet_potato_cultivar_with_sprouts.jpg",
    fact: "Russets account for about 40% of all US potato sales and are the standard for french fries.",
    quality: "vs Yukon Gold (4727): russets are starchy and fluffy when baked; Yukons are waxy and buttery. vs red potato (4073): reds hold their shape in salads. Avoid russets with green skin — that's solanine and tastes bitter.",
    memoryTip: "4-0-7-2: '40-72, russets do.'",
  },
  {
    plu: "4817",
    name: "Sweet Potato",
    variety: "Orange-fleshed",
    emoji: "🍠",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Ipomoea_batatas_006.JPG/960px-Ipomoea_batatas_006.JPG",
    fact: "Sweet potatoes are not related to potatoes — they're a morning glory, while potatoes are nightshades.",
    quality: "Choose firm, smooth tubers with no soft spots or sprouts. Orange-fleshed (most common in US) is sweeter and moister than white-fleshed varieties. Often mislabeled as 'yams' in stores.",
    memoryTip: "4-8-1-7: '48-17, sweet potato dream.'",
  },
  {
    plu: "3288",
    name: "Purple Japanese Sweet Potato",
    variety: "Stokes / Murasaki",
    emoji: "🍠",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Ipomoea_batatas_006.JPG/960px-Ipomoea_batatas_006.JPG",
    fact: "Japanese sweet potatoes have purple skin and creamy white flesh — drier and chestnut-sweet compared to orange varieties.",
    quality: "Reddish-purple skin and pale yellow-white flesh. Drier and more chestnut-flavoured than orange sweet potato (4817). Choose firm tubers with no soft spots. Best roasted whole.",
    memoryTip: "3-2-8-8: '32-88, Japanese sweet treat.'",
  },

  // ===== SQUASH / ZUCCHINI / EGGPLANT =====
  {
    plu: "4750",
    name: "Acorn Squash",
    variety: "Winter squash",
    emoji: "🎃",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Starr_070730-7820_Cucurbita_pepo.jpg/960px-Starr_070730-7820_Cucurbita_pepo.jpg",
    fact: "Acorn squash is named for its shape — a deeply ribbed acorn — and was cultivated by Indigenous peoples long before European contact.",
    quality: "Choose squash that feels heavy with deep green skin (often with an orange patch). Skin should be hard — soft skin or blemishes mean it's past its peak. Smaller squash are sweeter.",
    memoryTip: "4-7-5-0: '47-50, acorn nifty.'",
  },
  {
    plu: "4759",
    name: "Butternut Squash",
    variety: "Winter squash",
    emoji: "🎃",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Cucurbita_moschata_Butternut_2012_G2.jpg/960px-Cucurbita_moschata_Butternut_2012_G2.jpg",
    fact: "Butternut squash gets sweeter the longer it's stored — sugars develop for weeks after harvest.",
    quality: "Tan beige skin, bell-shaped. Choose squash that feels heavy with hard, dull (not glossy) skin. Glossy skin means underripe. Long necks have more flesh and fewer seeds.",
    memoryTip: "4-7-5-9: '47-59, butternut wine.'",
  },
  {
    plu: "4776",
    name: "Spaghetti Squash",
    variety: "Winter squash",
    emoji: "🎃",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Starr_070730-7822_Cucurbita_pepo.jpg/960px-Starr_070730-7822_Cucurbita_pepo.jpg",
    fact: "Spaghetti squash flesh separates into noodle-like strands when cooked — a pasta substitute long before low-carb diets existed.",
    quality: "Yellow oval squash with hard, smooth skin. Heavier feel = more flesh. Avoid soft spots, cracks, or green tinges (underripe).",
    memoryTip: "4-7-7-6: '47-76, spaghetti tricks.'",
  },
  {
    plu: "94782",
    name: "Organic Yellow Squash",
    variety: "Summer squash",
    emoji: "🥒",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Yellow_squash.jpg/960px-Yellow_squash.jpg",
    fact: "Yellow summer squash and zucchini are the same species (Cucurbita pepo) — only the colour differs.",
    quality: "Choose firm, glossy yellow squash, ideally smaller (under 8 inches) for tender flesh and small seeds. Larger ones are watery and bland. Skin should be unblemished.",
    memoryTip: "9-4-7-8-2: prefix 9 = organic; '47-82, yellow squash for you.'",
  },
  {
    plu: "4081",
    name: "Eggplant",
    variety: "Globe / Italian",
    emoji: "🍆",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/960px-Solanum_melongena_24_08_2012_%281%29.JPG",
    fact: "Eggplant got its English name from early white, egg-shaped European cultivars; the purple varieties came later.",
    quality: "Choose firm, glossy eggplants that feel light for their size — heavy ones are watery and seedy. Skin should bounce back when pressed. The stem cap should be green and fresh.",
    memoryTip: "4-0-8-1: '40-81, eggplant fun.'",
  },
  {
    plu: "94067",
    name: "Organic Zucchini",
    variety: "Green summer squash",
    emoji: "🥒",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/CSA-Striped-Zucchini.jpg/960px-CSA-Striped-Zucchini.jpg",
    fact: "Zucchini is technically a fruit (botanically a berry) and a single plant can produce dozens in a season.",
    quality: "Smaller zucchini (under 8 inches) are sweeter and less watery. Skin should be glossy and dark green; avoid wrinkled or soft spots. Heavy for its size means fresh.",
    memoryTip: "9-4-0-6-7: prefix 9 = organic; '40-67, zucchini heaven.'",
  },

  // ===== CUCUMBERS =====
  {
    plu: "4062",
    name: "English Cucumber",
    variety: "Long, seedless",
    emoji: "🥒",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/960px-ARS_cucumber.jpg",
    fact: "English cucumbers are sold plastic-wrapped to prevent moisture loss through their thin, edible skin.",
    quality: "Long, thin-skinned, seedless — usually wrapped in plastic. vs hothouse (4593): essentially the same product, sometimes labeled differently. Choose firm cucumbers with no soft or shrivelled ends.",
    memoryTip: "4-0-6-2: 'four-oh-six-two, cucumber's new.'",
  },
  {
    plu: "4593",
    name: "Hothouse Cucumber",
    variety: "Greenhouse-grown, seedless",
    emoji: "🥒",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/960px-ARS_cucumber.jpg",
    fact: "Hothouse cucumbers are grown in greenhouses without bees — the female-flowering plants don't need pollination to set fruit.",
    quality: "Long, thin-skinned, nearly seedless. Sweeter and milder than field cucumbers. Choose firm, dark green cucumbers — avoid soft or shrivelled ends. Often plastic-wrapped to retain moisture.",
    memoryTip: "4-5-9-3: '45-93, hothouse for me.'",
  },
  {
    plu: "94593",
    name: "Organic Hothouse Cucumber",
    variety: "Greenhouse, organic",
    emoji: "🥒",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/960px-ARS_cucumber.jpg",
    fact: "Organic greenhouse cucumbers use predatory mites and bumblebees instead of synthetic pesticides.",
    quality: "Same as conventional hothouse (4593), grown organically. Same look-and-feel test: firm, glossy, dark green, no soft ends.",
    memoryTip: "9-4-5-9-3: prefix 9 = organic; '45-93, organic hothouse free.'",
  },

  // ===== ARTICHOKE / ASPARAGUS / SWEET CORN =====
  {
    plu: "4762",
    name: "Artichoke",
    variety: "Globe, singles",
    emoji: "🌿",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Artichoke_J1.jpg/960px-Artichoke_J1.jpg",
    fact: "Artichokes are immature flower buds — left unpicked, they bloom into striking purple thistles.",
    quality: "Choose tight, compact heads that feel heavy and 'squeak' when squeezed. Leaves should be tightly closed and green; opening or browning means past peak. Stem should be firm.",
    memoryTip: "4-7-6-2: '47-62, artichoke crew.'",
  },
  {
    plu: "4080",
    name: "Asparagus",
    variety: "Bunch, conventional",
    emoji: "🌿",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Asparagus-Bundle.jpg/960px-Asparagus-Bundle.jpg",
    fact: "Asparagus can grow up to 10 inches in a single day under ideal conditions.",
    quality: "Choose bunches with tightly closed, dry tips and firm, straight stalks. Pencil-thin spears are most tender; thick spears are best peeled and roasted. Cut ends should be moist, not dry or splayed.",
    memoryTip: "4-0-8-0: '40-80, asparagus aplenty.'",
  },
  {
    plu: "4077",
    name: "Sweet Corn",
    variety: "Yellow, conventional",
    emoji: "🌽",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/79/VegCorn.jpg",
    fact: "An ear of corn has an even number of rows — always — due to the way kernels develop in pairs.",
    quality: "Choose ears with bright green, moist husks and golden-brown silk. Pierce a kernel — milky liquid means peak ripeness; watery means underripe, no liquid means starchy and past peak. Cook the same day for best sweetness.",
    memoryTip: "4-0-7-7: '40-77, corn from heaven.'",
  },
];
