// Each entry represents one PLU code. Fields:
//   plu         — IFPS-assigned 4-digit code (conventional produce starts with 3 or 4;
//                 prefix 9 = organic equivalent, e.g. 94011 for organic banana)
//   name        — common grocery display name
//   variety     — variety or sub-type shown in-game as a hint
//   emoji       — single emoji used as the visual representation
//   fact        — fun fact revealed after each round
//   description — (optional) longer description of the produce item
//   memoryTip   — (optional) mnemonic or trick for remembering this PLU

const PRODUCE_DATA = [
  {
    plu: "4011",
    name: "Banana",
    variety: "Yellow, conventional",
    emoji: "🍌",
    fact: "The most scanned PLU in US grocery history.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3082",
    name: "Broccoli",
    variety: "Fresh crown",
    emoji: "🥦",
    fact: "PLU codes starting with 3 or 4 are conventional produce.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4131",
    name: "Fuji Apple",
    variety: "Sweet & crisp",
    emoji: "🍎",
    fact: "Fujis were developed in Japan in the 1930s.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4133",
    name: "Gala Apple",
    variety: "Mildly sweet",
    emoji: "🍎",
    fact: "Gala apples originated in New Zealand.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4138",
    name: "Granny Smith",
    variety: "Tart green apple",
    emoji: "🍏",
    fact: "Named after Maria Ann 'Granny' Smith of Australia.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3107",
    name: "Navel Orange",
    variety: "Seedless, sweet",
    emoji: "🍊",
    fact: "The navel is actually a small undeveloped twin fruit.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4053",
    name: "Lemon",
    variety: "Conventional",
    emoji: "🍋",
    fact: "PLU 4053 covers most common lemon varieties.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4046",
    name: "Lime",
    variety: "Persian lime",
    emoji: "🍋",
    fact: "Most grocery limes are seedless Persian limes.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4225",
    name: "Hass Avocado",
    variety: "Small-medium",
    emoji: "🥑",
    fact: "Named after Rudolph Hass, who patented the tree in 1935.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3083",
    name: "Strawberry",
    variety: "Fresh pint",
    emoji: "🍓",
    fact: "Strawberries are the only fruit with seeds on the outside.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4022",
    name: "Green Grapes",
    variety: "Thompson seedless",
    emoji: "🍇",
    fact: "Thompson seedless are the world's most popular table grape.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3114",
    name: "Mango",
    variety: "Conventional",
    emoji: "🥭",
    fact: "Mangoes are the most consumed fruit in the world by weight.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3430",
    name: "Pineapple",
    variety: "Whole conventional",
    emoji: "🍍",
    fact: "It takes about 18 months to grow a single pineapple.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3421",
    name: "Watermelon",
    variety: "Seedless whole",
    emoji: "🍉",
    fact: "Watermelons are 92% water — hence the name.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4087",
    name: "Roma Tomato",
    variety: "Conventional",
    emoji: "🍅",
    fact: "Tomatoes are botanically a fruit but legally a vegetable in the US.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4062",
    name: "Cucumber",
    variety: "English cucumber",
    emoji: "🥒",
    fact: "Cucumbers are 96% water — even more than watermelon.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4562",
    name: "Carrot",
    variety: "Loose, conventional",
    emoji: "🥕",
    fact: "Carrots were originally purple before the orange variety was cultivated.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4072",
    name: "Russet Potato",
    variety: "Conventional",
    emoji: "🥔",
    fact: "Russets account for about 40% of all US potato sales.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4093",
    name: "Yellow Onion",
    variety: "Conventional",
    emoji: "🧅",
    fact: "Yellow onions caramelize best due to their high sugar content.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4608",
    name: "Garlic",
    variety: "Conventional bulb",
    emoji: "🧄",
    fact: "Garlic has been used medicinally for over 5,000 years.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3279",
    name: "Kiwi",
    variety: "Green, conventional",
    emoji: "🥝",
    fact: "Kiwis were originally called 'Chinese gooseberries'.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3035",
    name: "Peach",
    variety: "Yellow freestone",
    emoji: "🍑",
    fact: "Peaches are members of the rose family.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4409",
    name: "Bartlett Pear",
    variety: "Yellow, conventional",
    emoji: "🍐",
    fact: "Bartlett pears are the most common pear variety in the US.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "3329",
    name: "Blueberries",
    variety: "Fresh pint",
    emoji: "🫐",
    fact: "Blueberries are one of the few fruits native to North America.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4318",
    name: "Cantaloupe",
    variety: "Whole conventional",
    emoji: "🍈",
    fact: "Cantaloupes are named after Cantalupo, a papal estate near Rome.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4959",
    name: "Sweet Corn",
    variety: "Yellow, conventional",
    emoji: "🌽",
    fact: "Corn has exactly as many rows of kernels as silks at the top.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4688",
    name: "Red Bell Pepper",
    variety: "Conventional",
    emoji: "🫑",
    fact: "Red bell peppers have 3× more vitamin C than oranges.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4065",
    name: "Green Bell Pepper",
    variety: "Conventional",
    emoji: "🫑",
    fact: "Green bell peppers are simply unripe red, yellow, or orange peppers.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4070",
    name: "Celery",
    variety: "Conventional stalk",
    emoji: "🥬",
    fact: "Celery is 95% water and takes more energy to digest than it provides.",
    description: "",
    memoryTip: "",
  },
  {
    plu: "4519",
    name: "Honeydew Melon",
    variety: "Whole conventional",
    emoji: "🍈",
    fact: "Honeydew's pale green flesh is at peak sweetness when the rind turns creamy yellow.",
    description: "",
    memoryTip: "",
  },
];
