// Each entry represents one PLU code. Fields:
//   plu       — IFPS-assigned 4-digit code (conventional produce starts with 3 or 4;
//               prefix 9 = organic equivalent, e.g. 94011 for organic banana)
//   name      — common grocery display name
//   variety   — variety or sub-type shown in-game as a hint
//   emoji     — single emoji used as the visual representation
//   fact      — interesting tidbit revealed after each round
//   quality   — how to distinguish from similar varieties, or quality indicators
//   memoryTip — mnemonic or trick for remembering this PLU

const PRODUCE_DATA = [
  {
    plu: "4011",
    name: "Banana",
    variety: "Yellow, conventional",
    emoji: "🍌",
    fact: "The most scanned PLU in US grocery history.",
    quality: "Slightly green = ripens at home; bright yellow = ready now; brown-flecked = sweetest for baking. Avoid mushy, blackened stems.",
    memoryTip: "4-0-1-1: the easiest PLU to remember — just think 'the OG banana'.",
  },
  {
    plu: "3082",
    name: "Broccoli",
    variety: "Fresh crown",
    emoji: "🥦",
    fact: "Broccoli is 90% water and one of the most nutrient-dense vegetables by weight.",
    quality: "Choose dark green, tightly packed florets with no yellowing. Stems should snap crisply, not bend. Yellow florets mean it's past its peak.",
    memoryTip: "3-0-8-2: 'three-oh-eight-two, broccoli's true.'",
  },
  {
    plu: "4131",
    name: "Fuji Apple",
    variety: "Sweet & crisp",
    emoji: "🍎",
    fact: "Fujis were developed in Japan in the 1930s as a cross between Red Delicious and Ralls Janet.",
    quality: "vs Gala (4133): Fuji is larger, denser, and much crunchier with a honey-sweet flavour. Gala is softer, smaller, and milder. Choose firm Fujis with no soft spots.",
    memoryTip: "4-1-3-1: Fuji comes just after 4130 — one step up from nothing.",
  },
  {
    plu: "4133",
    name: "Gala Apple",
    variety: "Mildly sweet",
    emoji: "🍎",
    fact: "Gala apples originated in New Zealand and are now the top-selling apple variety in the US.",
    quality: "vs Fuji (4131): Gala is softer, smaller, and milder — better for kids. vs Honeycrisp: Gala is less expensive and less tart. Choose firm ones with bright red-orange stripes.",
    memoryTip: "4-1-3-3: Fuji is 4131, Gala is two higher — 4133. 'Gala goes further.'",
  },
  {
    plu: "4138",
    name: "Granny Smith",
    variety: "Tart green apple",
    emoji: "🍏",
    fact: "Named after Maria Ann 'Granny' Smith of Australia, who discovered the cultivar around 1868.",
    quality: "Unmistakably bright green and tart — no real lookalike in stores. Avoid apples with any yellow tinge (less tart, past peak). Great for baking because they hold shape.",
    memoryTip: "4-1-3-8: Granny is old — 38 is older than Fuji's 31 or Gala's 33.",
  },
  {
    plu: "3107",
    name: "Navel Orange",
    variety: "Seedless, sweet",
    emoji: "🍊",
    fact: "The navel is actually a small undeveloped twin fruit that grows inside the blossom end.",
    quality: "vs Valencia orange (4388): Navels have the belly-button end, are seedless, and are best for eating fresh. Valencias are juicier, have seeds, and are better for juicing. Choose heavy navels — weight equals juiciness.",
    memoryTip: "3-1-0-7: 'three-one-oh-seven, navel's heaven.'",
  },
  {
    plu: "4053",
    name: "Lemon",
    variety: "Conventional",
    emoji: "🍋",
    fact: "Lemons are a hybrid of bitter orange and citron, and do not exist as a wild species.",
    quality: "Eureka and Lisbon lemons look nearly identical in stores. Choose firm, heavy lemons with smooth, thin skin — the heavier they are, the juicier. Thick-skinned or light lemons yield less juice.",
    memoryTip: "4-0-5-3: 'four-oh-five-three, squeeze a lemon for me.'",
  },
  {
    plu: "4046",
    name: "Lime",
    variety: "Persian lime",
    emoji: "🍋",
    fact: "Persian limes — the standard grocery lime — are seedless because they are triploid hybrids.",
    quality: "Persian limes (4046) are large, seedless, and mild. Key limes are smaller, rounder, more aromatic, and rarely sold fresh in stores. Choose heavy limes with glossy, deep green skin — yellowing means overripe.",
    memoryTip: "4-0-4-6: lemon is 4053, lime is lower — 4046. Lime comes before lemon.",
  },
  {
    plu: "4225",
    name: "Hass Avocado",
    variety: "Small-medium",
    emoji: "🥑",
    fact: "Named after Rudolph Hass, a California mail carrier who patented the tree in 1935.",
    quality: "vs Florida avocado (4249): Hass is smaller, turns dark and pebbly when ripe, richer and creamier. Florida avocado is larger, stays green, and has lower fat. Ripe Hass yields to gentle pressure near the stem.",
    memoryTip: "4-2-2-5: 'forty-two twenty-five, the avocado's alive.'",
  },
  {
    plu: "3083",
    name: "Strawberry",
    variety: "Fresh pint",
    emoji: "🍓",
    fact: "Strawberries are the only fruit with seeds on the outside — around 200 per berry.",
    quality: "Choose fully red berries — white or green tips mean they were picked underripe and will never sweeten. Smell them at the store; ripe strawberries have a strong, sweet fragrance.",
    memoryTip: "3-0-8-3: broccoli is 3082, strawberry is one higher — 3083.",
  },
  {
    plu: "4022",
    name: "Green Grapes",
    variety: "Thompson seedless",
    emoji: "🍇",
    fact: "Thompson seedless grapes are also the primary grape used to make raisins.",
    quality: "vs red grapes (4498): green are crunchier and more tart, red are sweeter. Choose firm grapes still attached to stems. A faint white bloom (dusty coating) is natural and a sign of freshness.",
    memoryTip: "4-0-2-2: 'four-oh-two-two, green grapes for you.'",
  },
  {
    plu: "3114",
    name: "Mango",
    variety: "Conventional",
    emoji: "🥭",
    fact: "Mangoes are the most consumed fruit in the world by weight.",
    quality: "Don't judge by color — judge by feel. A ripe mango yields slightly to pressure near the stem. Tommy Atkins (red/green skin) vs Ataulfo (golden, kidney-shaped): Ataulfo is creamier and far less fibrous.",
    memoryTip: "3-1-1-4: 'three-one-one-four, mango to the core.'",
  },
  {
    plu: "3430",
    name: "Pineapple",
    variety: "Whole conventional",
    emoji: "🍍",
    fact: "It takes about 18 months to grow a single pineapple plant to harvest.",
    quality: "Ignore color — a green pineapple can be fully ripe. Judge by smell (sweet at the base) and firmness (slight give, not mushy). Gold Pineapples (Del Monte Extra Sweet) are sweeter and more golden than standard.",
    memoryTip: "3-4-3-0: '34-30, pineapple's born.'",
  },
  {
    plu: "3421",
    name: "Watermelon",
    variety: "Seedless whole",
    emoji: "🍉",
    fact: "Watermelons are 92% water — hence the name.",
    quality: "Look for a creamy yellow field spot (where it sat on the ground) — white or absent means it was picked too early. Should feel heavy for its size and sound hollow when thumped.",
    memoryTip: "3-4-2-1: close to pineapple (3430) — watermelon is a little under.",
  },
  {
    plu: "4087",
    name: "Roma Tomato",
    variety: "Conventional",
    emoji: "🍅",
    fact: "Tomatoes are botanically a fruit but were legally declared a vegetable by the US Supreme Court in 1893.",
    quality: "vs beefsteak (4664): Roma is firmer, meatier, and less watery — ideal for sauces and cooking. Beefsteak is larger, juicier, and better for slicing fresh. Choose Romas with deep red, unblemished skin.",
    memoryTip: "4-0-8-7: 'four-oh-eight-seven, Roma's heaven.'",
  },
  {
    plu: "4062",
    name: "Cucumber",
    variety: "English cucumber",
    emoji: "🥒",
    fact: "Cucumbers are 96% water — even more than watermelon.",
    quality: "English cucumbers (4062) are long, thin-skinned, and seedless — sold in plastic wrap. vs pickling cucumbers: shorter, bumpier, used for pickles. Choose firm cucumbers with no soft or shrivelled ends.",
    memoryTip: "4-0-6-2: 'four-oh-six-two, cucumber's new.'",
  },
  {
    plu: "4562",
    name: "Carrot",
    variety: "Loose, conventional",
    emoji: "🥕",
    fact: "Carrots were originally purple and white — the orange variety was cultivated in the Netherlands in the 17th century.",
    quality: "Loose carrots vs bagged baby carrots: loose are often fresher and more flavourful. Choose firm, smooth, bright orange carrots. Smaller diameter = more tender and sweet. Avoid limp or cracked ones.",
    memoryTip: "4-5-6-2: '45-62, carrots on cue.'",
  },
  {
    plu: "4072",
    name: "Russet Potato",
    variety: "Conventional",
    emoji: "🥔",
    fact: "Russets account for about 40% of all US potato sales and are the standard for french fries.",
    quality: "vs Yukon Gold (4060): Russets are starchy and fluffy when baked; Yukons are waxy and buttery. vs red potato (4073): reds hold their shape in salads. Avoid russets with green skin — that's solanine and tastes bitter.",
    memoryTip: "4-0-7-2: Yukon Gold is 4060, Russet is a bit higher — 4072.",
  },
  {
    plu: "4093",
    name: "Yellow Onion",
    variety: "Conventional",
    emoji: "🧅",
    fact: "Yellow onions become sweet and caramelized when cooked because their sulfur compounds convert to sugars.",
    quality: "vs white onion (4665): yellow is more complex and sweeter when cooked; white is sharper raw. vs red onion (3294): red is milder raw and used in salads. Choose firm, dry onions — avoid any with soft spots or green sprouts.",
    memoryTip: "4-0-9-3: 'four-oh-nine-three, yellow onion's free.'",
  },
  {
    plu: "4608",
    name: "Garlic",
    variety: "Conventional bulb",
    emoji: "🧄",
    fact: "Garlic has been used medicinally for over 5,000 years, including by Egyptian pyramid workers.",
    quality: "Choose firm, tight bulbs with dry papery skin. Avoid any soft spots or green sprouts — sprouted cloves taste bitter. Hardneck varieties have more complex flavour than softneck; softneck lasts longer.",
    memoryTip: "4-6-0-8: '46-08, garlic at the gate.'",
  },
  {
    plu: "3279",
    name: "Kiwi",
    variety: "Green, conventional",
    emoji: "🥝",
    fact: "Kiwis were originally called 'Chinese gooseberries' until New Zealand exporters rebranded them in the 1950s.",
    quality: "Green kiwi (3279) is tart and tangy with fuzzy brown skin. vs golden kiwi: smoother skin, sweeter, less acidic. Choose kiwis that yield slightly to pressure — rock-hard ones need several days on the counter to ripen.",
    memoryTip: "3-2-7-9: '32-79, kiwi's fine.'",
  },
  {
    plu: "3035",
    name: "Peach",
    variety: "Yellow freestone",
    emoji: "🍑",
    fact: "Peaches belong to the rose family, along with apples, pears, cherries, and almonds.",
    quality: "vs nectarine (3036): nectarines have smooth skin, peaches are fuzzy — flavour is nearly identical. Freestone pits separate easily (better for eating fresh); clingstone pits cling to the flesh. Choose peaches that smell fragrant and yield gently near the stem.",
    memoryTip: "3-0-3-5: peach is 3035, nectarine is one higher — 3036. Peach comes first.",
  },
  {
    plu: "4409",
    name: "Bartlett Pear",
    variety: "Yellow, conventional",
    emoji: "🍐",
    fact: "Bartlett pears are known as Williams pears in most of the world outside North America.",
    quality: "vs Bosc (4116): Bartlett is softer, juicier, and bell-shaped, turning yellow when ripe; Bosc is firmer, brown-skinned, and holds shape when cooked. vs D'Anjou (4020): D'Anjou stays green even when ripe. Check near the neck — ripe Bartlett yields gently there.",
    memoryTip: "4-4-0-9: '44-09, Bartlett's divine.'",
  },
  {
    plu: "3329",
    name: "Blueberries",
    variety: "Fresh pint",
    emoji: "🫐",
    fact: "Blueberries are one of the few fruits native to North America and were a staple food for Indigenous peoples.",
    quality: "Choose plump, firm, deep blue-purple berries with a silvery bloom (natural wax coating). Avoid red or green ones (underripe) and shrivelled or mushy ones. Shake the container — berries should move freely, not clump.",
    memoryTip: "3-3-2-9: '33-29, blueberries shine.'",
  },
  {
    plu: "4318",
    name: "Cantaloupe",
    variety: "Whole conventional",
    emoji: "🍈",
    fact: "Cantaloupes are named after Cantalupo, a papal estate near Rome where they were first cultivated in Europe.",
    quality: "vs honeydew (4519): cantaloupe has rough tan netting and orange flesh; honeydew has smooth pale skin and green flesh. Ripe cantaloupe smells sweet at the stem end and yields slightly. The stem end should have a smooth indent, not a stub.",
    memoryTip: "4-3-1-8: cantaloupe 4318, honeydew 4519 — cantaloupe is lower.",
  },
  {
    plu: "4959",
    name: "Sweet Corn",
    variety: "Yellow, conventional",
    emoji: "🌽",
    fact: "An ear of corn has an even number of rows — always — due to the way kernels develop in pairs.",
    quality: "Choose ears with bright green, moist husks and golden-brown silk. Pierce a kernel — milky liquid means peak ripeness; watery means underripe, no liquid means starchy and past peak. Cook the same day for best sweetness.",
    memoryTip: "4-9-5-9: '49-59, sweet corn's fine.'",
  },
  {
    plu: "4688",
    name: "Red Bell Pepper",
    variety: "Conventional",
    emoji: "🫑",
    fact: "Red bell peppers have 11 times more beta-carotene and 3 times more vitamin C than green bell peppers.",
    quality: "Red, yellow, and orange bells are fully ripened — sweeter and less bitter than green (4065), which is unripe. Red has an earthy sweetness; yellow is milder; orange is in between. Choose firm peppers that feel heavy with glossy skin.",
    memoryTip: "4-6-8-8: '46-88, red bell's great.'",
  },
  {
    plu: "4065",
    name: "Green Bell Pepper",
    variety: "Conventional",
    emoji: "🫑",
    fact: "Green bell peppers are simply unripe red, yellow, or orange peppers — picked early before they sweeten.",
    quality: "More bitter and less sweet than red (4688) or yellow bells because they haven't developed sugars yet. Choose firm, glossy, unwrinkled peppers. Wrinkling means moisture loss and age.",
    memoryTip: "4-0-6-5: green is 4065, red is 4688 — green is lower because it's less ripe.",
  },
  {
    plu: "4070",
    name: "Celery",
    variety: "Conventional stalk",
    emoji: "🥬",
    fact: "Celery was used as a medicinal plant in ancient Rome and Greece long before it became a food crop.",
    quality: "Choose firm, tightly packed stalks with fresh, green leaves — wilted leaves or hollow stalks mean it's old. Stalks should snap crisply, not bend. Lighter green stalks are more tender; darker outer stalks are more flavourful.",
    memoryTip: "4-0-7-0: '40-70, celery to go.'",
  },
  {
    plu: "4519",
    name: "Honeydew Melon",
    variety: "Whole conventional",
    emoji: "🍈",
    fact: "Unlike cantaloupes, honeydew melons do not slip from the vine when ripe — they must be cut.",
    quality: "vs cantaloupe (4318): honeydew has smooth, pale cream-green skin and green flesh; cantaloupe has rough tan netting and orange flesh. A ripe honeydew feels heavy, has a slightly waxy skin, and smells faintly sweet at the blossom end.",
    memoryTip: "4-5-1-9: honeydew 4519, cantaloupe 4318 — honeydew is higher.",
  },
];
